FROM rust:1.92.0

ARG USER_ID=1000

RUN apt update && \
    apt install -y gpg gnupg gpg-agent socat

RUN useradd -m -u ${USER_ID} rust

USER rust

WORKDIR /home/rust/app

RUN rustup component add rustfmt &&\
    cargo install cargo-watch

EXPOSE 8000 

CMD ["tail", "-f", "/dev/null"]